version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - "80:80"
    restart: always
    environment:
      - DOCKER_MYSQL_CONTAINER_NAME=${DOCKER_MYSQL_CONTAINER_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DOCKER_PHPMYADMIN_CONTAINER_NAME=${DOCKER_PHPMYADMIN_CONTAINER_NAME}
    volumes:
      - ./PrinterRoomSystem:/home/PrinterRoomSystem
    depends_on:
      - ${DOCKER_MYSQL_CONTAINER_NAME}
  
  mysql:
    image: mysql
    container_name: ${DOCKER_MYSQL_CONTAINER_NAME}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=PrinterRoomSystem
    volumes:
      - ./mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_PHPMYADMIN_CONTAINER_NAME}
    restart: always
    links:
      - ${DOCKER_MYSQL_CONTAINER_NAME}
    environment:
      PMA_HOST: ${DOCKER_MYSQL_CONTAINER_NAME}
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: /admin/database
